/**
* Proyecto Cierzo API
* Back-end API del Proyecto Cierzo
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param name 
 * @param authorID 
 * @param publishDate 
 * @param description 
 */
data class AlbumItemNew (
    val name: kotlin.String,
    val authorID: kotlin.String,
    val publishDate: java.time.LocalDateTime,
    val description: kotlin.String? = null
) {

}

