/**
* Proyecto Cierzo API
* Back-end API del Proyecto Cierzo
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.SongItem

/**
 * 
 * @param id 
 * @param name 
 * @param ownerID 
 * @param ownerName 
 * @param creationDate 
 * @param description 
 * @param songs 
 */
data class PlaylistItem (
    val id: kotlin.String,
    val name: kotlin.String,
    val ownerID: kotlin.String,
    val ownerName: kotlin.String,
    val creationDate: java.time.LocalDateTime,
    val description: kotlin.String,
    val songs: kotlin.Array<SongItem>
) {

}

