/**
* Proyecto Cierzo API
* Back-end API del Proyecto Cierzo
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param name 
 * @param lenght 
 * @param authorID 
 * @param albumID 
 * @param genre 
 */
data class SongItemNew (
    val name: kotlin.String,
    val lenght: kotlin.String,
    val authorID: kotlin.String,
    val albumID: kotlin.String,
    val genre: kotlin.Array<kotlin.String>
) {

}

