/**
* Proyecto Cierzo API
* Back-end API del Proyecto Cierzo
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.SongItem

/**
 * 
 * @param id 
 * @param name 
 * @param authorID 
 * @param authorName 
 * @param publishDate 
 * @param description 
 * @param songs 
 */
data class AlbumItem (
    val id: kotlin.String,
    val name: kotlin.String,
    val authorID: kotlin.String,
    val authorName: kotlin.String,
    val description: kotlin.String,
    val songs: kotlin.Array<SongItem>,
    val publishDate: java.time.LocalDateTime? = null
) {

}

