/**
* Proyecto Cierzo API
* Back-end API del Proyecto Cierzo
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param username 
 * @param name 
 * @param bio 
 */
data class FriendItem (
    val id: kotlin.String,
    val username: kotlin.String,
    val name: kotlin.String,
    val bio: kotlin.String
) {

}

